version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: neurokidDB
    restart: always
    environment:
      SA_PASSWORD: "Maplide123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"

  web:
    build: .
    container_name: neurokid_web
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "mssql://sa:Maplide123:1433/neurokidDB"
