# Generated by Django 5.0.14 on 2025-04-02 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
    ]
