# Generated by Django 5.0.14 on 2025-04-26 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_remove_nino_nombre_nino_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediccion', models.CharField(max_length=100)),
                ('probabilidad', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.juego')),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.nino')),
            ],
        ),
    ]
