# Generated by Django 5.0.14 on 2025-05-15 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0005_resultadoia'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoJuegoInvitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitado_id', models.CharField(max_length=100)),
                ('resultado', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.juego')),
            ],
        ),
    ]
