# Generated by Django 5.0.14 on 2025-05-22 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0006_intentojuegoinvitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEnvioReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(choices=[('email', 'Email'), ('descarga', 'Descarga directa')], max_length=20)),
                ('exito', models.BooleanField(default=False)),
                ('mensaje', models.TextField(blank=True)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.especialista')),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.nino')),
            ],
        ),
    ]
